const C=window.LEE_CONFIG, IMAGES=window.LEE_IMAGES;
const app=document.querySelector('#app'), progressText=document.querySelector('#progressText');
const uuid=()=>crypto.randomUUID();
const store={get:()=>JSON.parse(localStorage.getItem('lee-state')||'null'),set:s=>localStorage.setItem('lee-state',JSON.stringify(s)),clear:()=>localStorage.removeItem('lee-state')};
let state=store.get()||{step:'profile',participantId:uuid(),profile:null,scheme:[],answers:{},order:[],index:0,tab:'iea'};
const IEA={
 'Visual condition (no LEP)':['0 — Initial/factory condition','1 — Barely visible erosion or pinholes','2 — Localised pitting','3 — Widespread/coherent pits; some gouges','4 — Topcoat eroded; immediate underlying layer exposed','5 — Notable substrate/laminate damage'],
 'Visual condition (with LEP)':['0 — Initial/factory condition','1 — Light wear or reduced LEP adhesion','2 — Localised LEP damage / adhesive failure','3 — LEP compromised over a large area','4 — Topcoat delamination; underlying layer exposed','5 — Notable substrate damage'],
 'Mass loss':['0 — Negligible / none','1 — Coating loss <10%; laminate 0%','2 — Coating 10–50%; laminate 0%','3 — Coating 50–100%; laminate <10%','4 — Coating 100%; laminate 10–100%','5 — Coating 100%; laminate 100%'],
 'Aerodynamic performance':['0 — Normal surface roughness','1 — Region-2 power loss 0–1%','2 — Region-2 power loss 1–2%','3 — Region-2 power loss 2–3%','4 — Region-2 power loss 3–4%','5 — Region-2 power loss >4%'],
 'Blade integrity':['0 — No erosion affecting integrity','1 — Initial erosion of topcoat','2 — Erosion through topcoat','3 — Initial exposure of immediate laminate layers','4 — Erosion through immediate laminate layers','5 — Exposure of structural laminate layers']
};
const LERCAT=[['A','Minor localised damage / roughness'],['B','Discrete erosion'],['C','Continuous mild erosion'],['D','Continuous severe erosion'],['E','Very severe damage, including through-going holes']];
function save(){store.set(state)}
async function dbInsert(table,row){if(!C.SUPABASE_URL||!C.SUPABASE_ANON_KEY)return {demo:true};try{let r=await fetch(`${C.SUPABASE_URL}/rest/v1/${table}`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${C.SUPABASE_ANON_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text());return {ok:true}}catch(e){console.error(e);return {error:e.message}}}
function shuffled(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){save();progressText.textContent=state.step==='assess'?`Image ${state.index+1} of ${state.order.length}`:''; if(state.step==='profile')profile();else if(state.step==='scheme')scheme();else if(state.step==='assess')assess();else done()}
function profile(){app.innerHTML=`<section class=card><h1>${esc(C.CHALLENGE_TITLE)}</h1><p class=muted>You will classify approximately 30 leading-edge erosion images using IEA Task 46, LERCat, and a classification scheme that you define yourself.</p><div class=note>This prototype stores participant responses privately in Supabase when configured. Other participants cannot view results.</div><form id=p><div class=grid>${[['name','Name','text'],['organisation','Organisation','text'],['email','Email','email'],['orgType','Organisation type','text'],['country','Country','text']].map(([n,l,t])=>`<div class=field><label>${l}</label><input name=${n} type=${t} required></div>`).join('')}</div><label class=small><input type=checkbox name=consent required> I consent to my submitted information being used for this research challenge.</label><div class=actions><button class="btn primary">Continue</button></div></form></section>`;document.querySelector('#p').onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));state.profile=f;await dbInsert('participants',{id:state.participantId,name:f.name,organisation:f.organisation,email:f.email,organisation_type:f.orgType,country:f.country,consented:true});state.step='scheme';render()}}
function scheme(){if(!state.scheme.length)state.scheme=[{id:uuid(),name:'Overall erosion severity',levels:[{id:uuid(),label:'Level 0',description:'No visible erosion'},{id:uuid(),label:'Level 1',description:'Minor visible erosion'}]}];app.innerHTML=`<section class=card><h1>Define your own classification scheme</h1><p class=muted>Add any number of evaluation criteria. Each criterion can have any number of severity levels; every level needs a description. Your scheme is locked once image assessment starts.</p><div id=criteria></div><button class=btn id=addCriterion>+ Add criterion</button><div class=actions><button class="btn primary" id=start>Start image assessment</button></div></section>`;drawScheme();document.querySelector('#addCriterion').onclick=()=>{state.scheme.push({id:uuid(),name:'',levels:[{id:uuid(),label:'Level 0',description:''},{id:uuid(),label:'Level 1',description:''}]});drawScheme()};document.querySelector('#start').onclick=async()=>{readScheme();if(!state.scheme.every(c=>c.name.trim()&&c.levels.length&&c.levels.every(l=>l.label.trim()&&l.description.trim())))return alert('Please name every criterion and describe every severity level.');await dbInsert('events',{participant_id:state.participantId,event_type:'scheme',payload:state.scheme});state.order=C.RANDOMISE_IMAGES?shuffled(IMAGES.map(x=>x.id)):IMAGES.map(x=>x.id);state.step='assess';state.index=0;render()}}
function drawScheme(){document.querySelector('#criteria').innerHTML=state.scheme.map((c,ci)=>`<div class=scheme-row data-ci=${ci}><div class=field><label>Criterion ${ci+1}</label><input class=cname value="${esc(c.name)}"></div><div class=levelsedit>${c.levels.map((l,li)=>`<div class=level-row data-li=${li}><input class=llabel value="${esc(l.label)}" placeholder="Severity level"><input class=ldesc value="${esc(l.description)}" placeholder="Required description"><button class="btn danger rmlevel" type=button>×</button></div>`).join('')}</div><button class="btn addlevel" type=button>+ Level</button> <button class="btn danger rmcriterion" type=button>Remove criterion</button></div>`).join('');document.querySelectorAll('.addlevel').forEach((b,i)=>b.onclick=()=>{readScheme();state.scheme[i].levels.push({id:uuid(),label:`Level ${state.scheme[i].levels.length}`,description:''});drawScheme()});document.querySelectorAll('.rmcriterion').forEach((b,i)=>b.onclick=()=>{readScheme();if(state.scheme.length>1)state.scheme.splice(i,1);drawScheme()});document.querySelectorAll('.rmlevel').forEach(b=>b.onclick=()=>{readScheme();let p=b.closest('.scheme-row'),r=b.closest('.level-row'),ci=+p.dataset.ci,li=+r.dataset.li;if(state.scheme[ci].levels.length>1)state.scheme[ci].levels.splice(li,1);drawScheme()})}
function readScheme(){document.querySelectorAll('.scheme-row').forEach((r,ci)=>{state.scheme[ci].name=r.querySelector('.cname').value; r.querySelectorAll('.level-row').forEach((lr,li)=>{state.scheme[ci].levels[li].label=lr.querySelector('.llabel').value;state.scheme[ci].levels[li].description=lr.querySelector('.ldesc').value})});save()}
function answerKey(){return state.order[state.index]}function getAns(){let k=answerKey();return state.answers[k]||(state.answers[k]={iea:{},lercat:'',own:{}})}
function assess(){let id=answerKey(),img=IMAGES.find(x=>x.id===id),a=getAns(),pct=Math.round((state.index/state.order.length)*100);app.innerHTML=`<div class=progressbar><div style="width:${pct}%"></div></div><section class=assessment><div class=imagebox><img src="${img.url}" alt="Wind turbine blade leading edge erosion assessment image" style="object-position:${img.crop.x}% ${img.crop.y}%;transform:scale(${img.crop.zoom})"></div><div class=card><h2>Assessment ${state.index+1}</h2><div class=tabs>${[['iea','IEA Task 46'],['lercat','LERCat'],['own','Your scheme']].map(([k,l])=>`<button class="tab ${state.tab===k?'active':''}" data-tab=${k}>${l}</button>`).join('')}</div><div id=panel></div><div class=actions><button class=btn id=prev ${state.index===0?'disabled':''}>Previous</button><button class="btn primary" id=next>${state.index===state.order.length-1?'Finish':'Next image'}</button></div></div></section>`;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});drawPanel();document.querySelector('#prev').onclick=()=>{state.index--;render()};document.querySelector('#next').onclick=async()=>{if(!complete(a))return alert('Please complete all three classification sections for this image. “Cannot determine from image” is available for IEA criteria that cannot be inferred reliably.');await dbInsert('events',{participant_id:state.participantId,event_type:'assessment',image_id:id,payload:a});if(state.index===state.order.length-1){await dbInsert('events',{participant_id:state.participantId,event_type:'submitted',payload:{completed_at:new Date().toISOString(),image_order:state.order}});state.step='done'}else state.index++;render()}}
function complete(a){return Object.keys(IEA).every(k=>a.iea[k]!==undefined)&&a.lercat&&state.scheme.every(c=>a.own[c.id])}
function drawPanel(){let a=getAns(),p=document.querySelector('#panel');if(state.tab==='iea'){p.innerHTML=`<p class=muted>Rate each IEA criterion separately. For photograph-only evidence, use “Cannot determine” when the criterion cannot be supported by the image.</p>${Object.entries(IEA).map(([c,ls])=>`<div class=criterion><h3>${c}</h3><div class=levels>${[...ls,'Cannot determine from image'].map((l,i)=>`<label class="choice ${a.iea[c]===l?'selected':''}"><input type=radio name="iea-${esc(c)}" value="${esc(l)}" ${a.iea[c]===l?'checked':''}>${esc(l)}</label>`).join('')}</div></div>`).join('')}`;p.querySelectorAll('input').forEach(x=>x.onchange=()=>{a.iea[x.name.slice(4)]=x.value;save();drawPanel()})}else if(state.tab==='lercat'){p.innerHTML=`<p class=muted>Select the LERCat category that best matches the visible leading-edge condition.</p><div class=levels>${LERCAT.map(([k,d])=>`<label class="choice ${a.lercat===k?'selected':''}"><input type=radio name=lercat value=${k} ${a.lercat===k?'checked':''}><strong>${k}</strong><br><span class=small>${d}</span></label>`).join('')}</div>`;p.querySelectorAll('input').forEach(x=>x.onchange=()=>{a.lercat=x.value;save();drawPanel()})}else{p.innerHTML=`<p class=muted>Apply the classification scheme you defined before the challenge.</p>${state.scheme.map(c=>`<div class=criterion><h3>${esc(c.name)}</h3><div class=levels>${c.levels.map(l=>`<label class="choice ${a.own[c.id]===l.id?'selected':''}"><input type=radio name="own-${c.id}" value="${l.id}" ${a.own[c.id]===l.id?'checked':''}><strong>${esc(l.label)}</strong><br><span class=small>${esc(l.description)}</span></label>`).join('')}</div></div>`).join('')}`;p.querySelectorAll('input').forEach(x=>x.onchange=()=>{a.own[x.name.slice(4)]=x.value;save();drawPanel()})}}
function done(){app.innerHTML=`<section class=card><div class=complete>✓</div><h1 style="text-align:center">Submission complete</h1><p class=muted style="text-align:center">Thank you. Results have been submitted and are not displayed to participants.</p><div class=actions><button class=btn id=reset>Clear this browser's local challenge data</button></div></section>`;document.querySelector('#reset').onclick=()=>{if(confirm('Clear local challenge data? This does not delete submitted researcher data.')){store.clear();location.reload()}}}
render();
